version: '4'
services:
  mongodb:
    image: mysql:8.3.0
    container_name: mysql
    ports:
       - "3306:3306"
    environment:
        MONGO_INITDB_ROOT_USERNAME: mysql
    volumes:
        - ./mysql:/var/lib/mysql

